FOOD_SITE/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

from django.conf.urls.static import static
from django.conf import Settings, settings

from django.contrib.auth import views as authentication_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),

    # users views
    path('register/', views.register, name='register'),
    path('login/', authentication_view.LoginView.as_view(
        template_name="users/login.html"), name='login'),
    path('logout/', authentication_view.LogoutView.as_view(
        template_name="users/logout.html"), name='logout'),
    path('profile/', views.profilepage, name='profile')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from .import views

app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('item/', views.item, name='item'),
    path('<int:pk>/', views.FoddDetail.as_view(), name='detail'),
    path('add', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to="profile_pictures", default="profilepic.jpg")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from . models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# def index(request):
#     item_list = Item.objects.all()
#     return render(request, 'food/index.html', {'item_list': item_list})


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse("hello world items")


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item
#     }
#     return render(request, 'food/detail.html', context)


class FoddDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form})

# this is class based view for create view


class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'item': item, 'form': form})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Welcome {username},your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <nav class='navbar navbar-dark bg-dark'>
        <a href="#" class="navbar-brand">FoodKart</a>
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="#" class="nav-item nav-link">View Item</a>

            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>

            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}

        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}


    {% block body %}
    {% endblock body %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
</body>

</html>

food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" class="card" width="300px" height="300px">
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>Rs.{{object.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock body %}

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    {% block body %}
    {% for item in item_list %}
    <div class="row my-md-3 shadow-lg py-3">
        <div class="col-md-3 offset-md-2 ">
            <img src="{{item.item_image}}" height="150px" width="250px"
                class="card shadow-sm border-dark border border-2 rounded-3">
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>Rs.{{item.item_price}}</h6>
            <h6>{{item.user_name}}</h6>
        </div>
        <div class="col-md-2 my-md-auto">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>

    {% endfor %}

    {% endblock body %}




</body>

</html>

food/templates/food/item-delete.html
<form action="" method='POST'>
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends "food/base.html" %}

{% block body %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-center bg-info fw-bold h1">
                    <div class="card-title">Add item</div>
                </div>
                <div class="card-body">

                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group p-1 text-center fw-bolder text-dark">
                            {{field.name}}
                            <br>
                            {{field}}
                        </div>
                        {% endfor %}
                        <br>
                        <button class="btn-info offset-md-5 py-1 my-1" type="submit">Add </button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock body %}

users/templates/users/login.html
{% extends "food/base.html" %}

{% block body %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-center bg-info fw-bold h1">
                    <div class="card-title">Login</div>
                </div>
                <div class="card-body">

                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group p-1">
                            {{field.name}}
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn-info offset-md-5 py-1 my-1" type="submit">Login</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock body %}

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>


<img src="{{user.profile.image.url}}" height="150px" width="150px" >

users/templates/users/register.html
{% extends "food/base.html" %}

{% block body %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-center bg-info fw-bold h1">
                    <div class="card-title">Register</div>
                </div>
                <div class="card-body">

                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group p-1 text-center">
                            {{field.name}}
                            <br>
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn-info offset-md-5 py-1 my-1" type="submit">Signup</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock body %}